import React from "react";
import CariComp from "../components/Cari/CariComp";
import Head from "next/head";

const cari = () => {
  return (
    <>
      <Head>
        <title>Pengona Software</title>
        <meta name="description" content="Generated by Pengona" />
      </Head>
      <main className="w-full flex flex-col lg:px-8 lg:py-16 md:px-6 md:py-12 px-0 bg-blue-gray-100 min-h-full  ">
        <CariComp/>
      </main>
    </>
  );
};

export default cari;
