import Head from "next/head";
import Stok from "../components/Home/Stok/Stok";

export default function Home() {


  return (
    <>
      <Head>
        <title>Pengona Software</title>
        <meta name="description" content="Generated by Pengona" />
      </Head>
      <main className="w-full flex flex-col lg:px-8 lg:py-16 md:px-6 md:py-12 px-0 bg-blue-gray-100 min-h-full  ">

       <Stok/>
        {/* <div className="flex justify-center items-center w-full">
          {status && status === "error" && (
            <Alert
              message="Error"
              description="E-posta veya şifre bilgileri yanlış"
              type="error"
              showIcon
              closable
            />
          )}
          <div>
            <h2>Login</h2>
            <input
              type="email"
              placeholder="Email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <button onClick={handleLogin} disabled={isLoading}>
              {isLoading ? "Loading..." : "Login"}
            </button>
          </div>
        </div> */}
      </main>
    </>
  );
}
